CREATE TABLE PRODUCT (
		PRODUCT_ID INTEGER NOT NULL,
		MANUFACTURER_ID INTEGER NOT NULL,
		PRODUCT_CODE CHAR(2) NOT NULL,
		PURCHASE_COST DECIMAL(12 , 0),
		QUANTITY_ON_HAND INTEGER,
		MARKUP DECIMAL(4 , 0),
		AVAILABLE VARCHAR(5),
		DESCRIPTION VARCHAR(50)
	);

CREATE UNIQUE INDEX SQL130323125629620 ON PRODUCT (PRODUCT_ID ASC);

ALTER TABLE PRODUCT ADD CONSTRAINT SQL130323125629620 PRIMARY KEY (PRODUCT_ID);
