CREATE TABLE PURCHASE_ORDER (
		ORDER_NUM INTEGER NOT NULL,
		CUSTOMER_ID INTEGER NOT NULL,
		PRODUCT_ID INTEGER NOT NULL,
		QUANTITY SMALLINT,
		SHIPPING_COST DECIMAL(12 , 0),
		SALES_DATE DATE,
		SHIPPING_DATE DATE,
		FREIGHT_COMPANY VARCHAR(30)
	);

CREATE UNIQUE INDEX SQL130323125649590 ON PURCHASE_ORDER (ORDER_NUM ASC);

ALTER TABLE PURCHASE_ORDER ADD CONSTRAINT SQL130323125649590 PRIMARY KEY (ORDER_NUM);
